baseurl = "https://conorhodder.github.io"
title = "Hodder's Amusements"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
    pagerSize = 20

[services]
    [services.disqus]
        shortname = "engineering"

    [markup.highlight]
        style = "github-dark"

    [params]
        author = "Conor Hodder"
        info = "Backend & Devops Engineer"
        description = "Conor Hodders's personal website"
        keywords = "blog,developer,personal"

        avatarurl = "images/avatar.jpg"
        #gravatar = "john.doe@example.com"

        faviconSVG = "/img/favicon.svg"
        favicon_32 = "/img/favicon.png"
        #favicon_16 = "/img/favicon-16x16.png"

        since = 2019

        enableTwemoji = true

        colorScheme = "auto"
        hidecolorschemetoggle = false

        # customCSS = ["css/custom.css"]
        # customSCSS = ["scss/custom.scss"]
        # customJS = ["js/custom.js"]

    [taxonomies]
        category = "categories"
        series = "series"
        tag = "tags"
        author = "authors"

    # Social links
    [[params.social]]
        name = "Github"
        icon = "fa-brands fa-github fa-2x"
        weight = 1
        url = "https://github.com/conorhodder/"

    [[params.social]]
        name = "LinkedIn"
        icon = "fa-brands fa-linkedin fa-2x"
        weight = 1
        url = "https://www.linkedin.com/in/conorhodder/"

    # Menu links
    [[menu.main]]
        name = "Engineering Blog"
        weight = 1
        url  = "engineering/"
